In [1]:
import numpy as np
A= np.random.randn(4,3)
print(A)

[[-0.04921006  0.69359483  2.7822109 ]
 [ 0.1628923  -0.09443848  2.80175785]
 [ 0.35760921  2.13912346 -0.15741499]
 [-0.39371912  2.06466653 -1.46926835]]


In [3]:
B = np.sum(A, axis = 1, keepdims = True) 
print(B)

[[3.42659567]
 [2.87021166]
 [2.33931768]
 [0.20167906]]
